check workflow

diff --git a/.github/workflows/scheduled_workflow.yml b/.github/workflows/scheduled_workflow.yml
--- a/.github/workflows/scheduled_workflow.yml
+++ b/.github/workflows/scheduled_workflow.yml
@@ -144,8 +144,8 @@ jobs:
           echo "Setting gateway: $GATEWAY"
 
           echo "Running sudo ip route add..."
-          sudo ip route add 192.168.0.0/24 via $GATEWAY dev ppp0
-          sudo ip route add default via $GATEWAY dev ppp0
+          sudo ip route add 192.168.0.0/24 via $GATEWAY dev ppp0 || { echo "Error adding route"; exit 1; }
+          sudo ip route add default via $GATEWAY dev ppp0 || { echo "Error adding default route"; exit 1; }
 
           
           ip route
